export const portfolioProjects = [
  {
    id: "nexus",
    title: "Nexus Fintech",
    clientType: "Fintech startup",
    description: "Modern dashboard and marketing site that built trust and sign-ups.",
    gradient: "from-cyan-500/20 to-blue-600/20",
    accent: "#00d4ff",
    brief: "A new fintech needed a professional web presence and a simple dashboard for early users.",
    solution: "We built a bold marketing site with clear value props and a clean, secure dashboard UI.",
    outcome: "40% increase in sign-up conversion and a product that scaled to Series A.",
  },
  {
    id: "luna",
    title: "Luna Cosmetics",
    clientType: "E-commerce / beauty",
    description: "Online store that reflects the brand and converts browsers into buyers.",
    gradient: "from-pink-500/20 to-rose-600/20",
    accent: "#ff00aa",
    brief: "Luna wanted to move from marketplace-only to their own store without losing their look.",
    solution: "Custom e-commerce with their visual identity, fast checkout, and inventory sync.",
    outcome: "Live in days; first-month sales beat their previous channel.",
  },
  {
    id: "apex",
    title: "Apex Fitness",
    clientType: "Local business / gym",
    description: "Local gym site that ranks and converts—book classes, see schedules, join online.",
    gradient: "from-amber-500/20 to-orange-600/20",
    accent: "#ffb800",
    brief: "Apex needed a site that showed class times, allowed bookings, and brought in local members.",
    solution: "Mobile-first site with booking, SEO for local terms, and simple member area.",
    outcome: "Higher local search visibility and 25% more class bookings in 3 months.",
  },
  {
    id: "verdant",
    title: "Verdant Eco",
    clientType: "Sustainability brand",
    description: "Landing and motion that communicates mission and drives newsletter sign-ups.",
    gradient: "from-emerald-500/20 to-teal-600/20",
    accent: "#00d4ff",
    brief: "Verdant needed a single strong page to explain their mission and grow their list.",
    solution: "Scroll-driven storytelling with subtle motion and a clear CTA to subscribe.",
    outcome: "Doubled newsletter sign-ups and stronger brand recognition.",
  },
  {
    id: "frame",
    title: "Frame Studio",
    clientType: "Creative / portfolio",
    description: "Portfolio and CMS so the team can update work without touching code.",
    gradient: "from-violet-500/20 to-purple-600/20",
    accent: "#ff00aa",
    brief: "A design studio wanted a portfolio that they could update themselves.",
    solution: "Custom design with a simple CMS: add projects, images, and case studies in minutes.",
    outcome: "Team updates the site weekly; no developer needed for content.",
  },
  {
    id: "ember",
    title: "Ember Kitchen",
    clientType: "Restaurant / hospitality",
    description: "Modern restaurant site with menus, reservations, and local flavour that brings diners in.",
    gradient: "from-orange-600/20 to-amber-700/20",
    accent: "#ffb800",
    brief: "Ember Kitchen needed a site that showcased their menu, handled table bookings, and attracted local diners.",
    solution: "Warm, inviting design with online menu, reservation integration, and strong local SEO.",
    outcome: "Reservations up 35%; the site now drives most new bookings.",
  },
] as const;
