/**
 * Live sample sites built by Evolution Media.
 * Used in the portfolio section as external links.
 */

export const sampleSites = [
  {
    id: "luxe-estates",
    title: "Luxe Estates",
    clientType: "Real estate",
    description: "Luxury real estate agency—property listings, filters, services, and contact.",
    url: "https://real-estate-agency-lemon.vercel.app/",
    image: "/portfolio-samples/luxe-estates.jpg",
    accent: "#00d4ff",
    gradient: "from-sky-500/20 to-cyan-600/20",
  },
  {
    id: "premier-dental",
    title: "Premier Dental Care",
    clientType: "Healthcare",
    description: "Modern dental practice site—services, team, testimonials, and booking.",
    url: "https://dental-practice-xi.vercel.app/",
    image: "/portfolio-samples/premier-dental.jpg",
    accent: "#0ea5e9",
    gradient: "from-slate-400/20 to-blue-500/20",
  },
  {
    id: "bambinos",
    title: "Bambinos",
    clientType: "Family / play",
    description: "Kids sensory and messy play zone—sessions, pricing, and booking.",
    url: "https://bambinos-ten.vercel.app/",
    image: "/portfolio-samples/bambinos.jpg",
    accent: "#a855f7",
    gradient: "from-purple-500/20 to-pink-600/20",
  },
  {
    id: "travel-bug",
    title: "Travel Bug",
    clientType: "Travel",
    description: "Independent travel advisor—services, offers, and trip planning.",
    url: "https://travelbug-v1.vercel.app/",
    image: "/portfolio-samples/travel-bug.jpg",
    accent: "#f59e0b",
    gradient: "from-amber-500/20 to-orange-600/20",
  },
  {
    id: "evolution-it",
    title: "Evolution IT",
    clientType: "IT / B2B",
    description: "Managed IT and cybersecurity—services, pricing, and assessments.",
    url: "https://evolution-it-website.vercel.app/",
    image: "/portfolio-samples/evolution-it.jpg",
    accent: "#00d4ff",
    gradient: "from-cyan-500/20 to-blue-600/20",
  },
  {
    id: "golden-dragon",
    title: "Golden Dragon",
    clientType: "Restaurant",
    description: "Chinese restaurant—menu, ordering, and private events.",
    url: "https://golden-dragon-chinese-ukrt.vercel.app/",
    image: "/portfolio-samples/golden-dragon.jpg",
    accent: "#dc2626",
    gradient: "from-red-600/20 to-amber-700/20",
  },
  {
    id: "oak-ember",
    title: "The Oak & Ember",
    clientType: "Restaurant",
    description: "Modern dining—seasonal food, bookings, and online ordering.",
    url: "https://restaurant-sigma-peach.vercel.app/",
    image: "/portfolio-samples/oak-ember.jpg",
    accent: "#f97316",
    gradient: "from-amber-600/20 to-orange-700/20",
  },
  {
    id: "luna-co",
    title: "Luna & Co Hair Studio",
    clientType: "Hair salon",
    description: "Premium hair studio—services, team, gallery, and booking.",
    url: "https://salon-opal-zeta.vercel.app/",
    image: "/portfolio-samples/luna-co.jpg",
    accent: "#a855f7",
    gradient: "from-purple-500/20 to-pink-600/20",
  },
] as const;
